server:
  port: 8081

spring:
  application:
    name: display

# hystrix Timeout 시간 조정하기
hystrix:
  command:
    productInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      # 10초 동안 20개(default) 이상의 호출이 발생했을 때 50% 이상의 호출에서 에러가 발생하면 Circuit Open
      circuitBreaker:
        requestVolumeThreshold: 1      # default 20
        errorThresholdPercentage: 50   # default 50
    FeignProductRemoteService#getProductInfo(String):
      execution:
        isolation:
          thread:
            timeoutInMilliSeconds: 3000 # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1      # default 20
        errorThresholdPercentage: 50   # default 50

product:
  ribbon:
    # 서버 주소는 이제 Eureka Server 에서 가져와라!
    #listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address(로컬 테스트 시 불필요)

# feign을 통한 메소드 하나하나가 Hystrix command로서 호출됨.
feign:
  hystrix:
    enabled: true